### ISSUE TITLE
Exception thrown for invalid anchor/alias syntax

### ISSUE THREAD

**Issue by oveee92** [oveee92/vaulti#5]
Using faulty syntax for anchors and aliases, like:

```yaml
test1: &foo
  one: one
  two: two

test2:
  <<: &foo #<-- This should have been an asterisk, not an ampersand
  two: new_two
```

causes vaulti to throw a `ruamel.yaml.constructor.ConstructorError` exception;

Should be caught and offered to re-edit the file the same way other yaml errors are caught.
